project_name: "infill_cnn_dm_seq"
data:
  train_data_src: "data/cnn_dm_original/train.source"
  train_data_trg: "data/cnn_dm_original/train.target"
  eval_data_src: "data/cnn_dm_original/val.source"
  eval_data_trg: "data/cnn_dm_original/val.target"
  test_data_src: "data/cnn_dm_original/test.source"
  test_data_trg: "data/cnn_dm_original/test.target"
  debug_data_src: "data/cnn_dm_original/debug.source"
  debug_data_trg: "data/cnn_dm_original/debug.target"
  cache_dir: "data/cnn_dm_original/cache"
  processor: "seq"
train:
  output_dir: "ckpt/cnndm/infill"
  logging_dir: "./logs"
  do_train: True
  num_train_epochs: 10
  per_device_train_batch_size: 8
  logging_strategy: "steps"
  logging_steps: 1500
  save_strategy: "steps"
  save_steps: 10000
  save_total_limit: 5
  report_to: "wandb"
eval:
  do_eval: True
  do_predict: True
  predict_with_generate: True
  per_device_eval_batch_size: 16
  load_best_model_at_end: True
  evaluation_strategy: "steps"  # Add this line
  eval_steps: 10000
  metric_for_best_model: "rouge1"
  greater_is_better: True
test:
  per_device_eval_batch_size: 16
  test_output_dir: "./results"
  write_result: True
  write_to_file: "./results/s2sft_cnndm.txt"
  best_model_path: "ckpt/cnndm/infill/best_model"